pipeline {
    agent any
    stages {
        stage ('comile stage') {
            steps{
                withMaven(maven: 'apache-maven-3.6.1'){
                    sh 'mvn clean compile'
                }
            }

        }
        
        stage ('Testing Stage') {
            steps{
                withMaven(maven: 'apache-maven-3.6.1'){
                    sh 'mvn test'
				}
            }
        }

    }
}